import type { NextConfig } from "next";

// ---------------------------------------------------------------------------
// Content Security Policy
// ---------------------------------------------------------------------------
//
// Directives justified by actual project usage (Next.js 16, App Router):
//
//  default-src 'none'
//    Deny everything not explicitly allowed. Fail-safe baseline.
//
//  script-src 'self'
//    Next.js bundles (/_next/static/chunks/…) and /sw.js are all served from
//    the same origin. No third-party scripts. No eval/Function() used anywhere.
//    Next.js 16 no longer needs 'unsafe-inline' for script tags when using the
//    App Router (inline scripts are replaced by module scripts or removed).
//
//  style-src 'self' 'unsafe-inline'
//    Tailwind v4 output is bundled and served from /_next/static/ ('self').
//    However, two React components inject dynamic inline style= attributes:
//      • mobile-nav.tsx  → style={{ gridTemplateColumns: `repeat(…)` }}
//      • stat-cards.tsx  → style={{ width: `${pct}%` }}
//    React writes these as inline style attributes which require 'unsafe-inline'.
//    A nonce/hash cannot be applied to element-level style= props; the only
//    alternative would be rewriting those components to use CSS custom props,
//    which is out of scope here.
//
//  img-src 'self' data:
//    All images are self-hosted (/logo.png, /icon*.png, /icon.svg, /_next/image).
//    data: is required for QR-code DataURLs generated by qrcode.toDataURL()
//    and displayed as <img src="data:image/png;base64,…"> on the QR-code pages.
//
//  font-src 'self'
//    next/font/google downloads and self-hosts Geist & Geist_Mono at build time
//    (served from /_next/static/media/). No runtime request to fonts.gstatic.com.
//
//  connect-src 'self'
//    Server Actions are POSTed to the same origin.
//    No client-side calls to Firebase, analytics, or any third-party API.
//    (All Firebase/Firestore/Storage traffic happens server-side only.)
//
//  worker-src 'self'
//    The PWA service worker /sw.js is registered from the same origin.
//
//  manifest-src 'self'
//    /manifest.json (PWA web app manifest) is served from the same origin.
//
//  frame-ancestors 'none'
//    Redundant with X-Frame-Options: DENY but required for CSP-aware browsers
//    that prefer frame-ancestors over X-Frame-Options.
//
//  base-uri 'none'
//    Prevents injection of a <base> tag that could hijack relative URLs.
//
//  form-action 'self'
//    All HTML forms (login, sign-out, leave requests, …) POST to the same origin.
//    Explicitly blocks form hijacking to external URLs.
//
//  object-src 'none'
//    No Flash / plugins / PDFs embedded via <object>/<embed>/<applet>.
//    (PDF download links use <a href>, not <object>.)
//
// Report-Only is used for the initial local test so that no existing
// functionality breaks. Switch to Content-Security-Policy once violations
// are confirmed to be zero in production.
// ---------------------------------------------------------------------------

const CSP = [
  "default-src 'none'",
  "script-src 'self'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self'",
  "worker-src 'self'",
  "manifest-src 'self'",
  "frame-ancestors 'none'",
  "base-uri 'none'",
  "form-action 'self'",
  "object-src 'none'",
].join("; ");

const securityHeaders = [
  // Empêche l'application d'être chargée dans une <iframe> tierce (clickjacking).
  { key: "X-Frame-Options", value: "DENY" },
  // Empêche le navigateur de deviner un type MIME différent de celui déclaré.
  { key: "X-Content-Type-Options", value: "nosniff" },
  // Limite les informations envoyées dans l'en-tête Referer vers d'autres origines.
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  // Désactive par défaut les API sensibles (caméra, micro, géoloc) non utilisées par l'app.
  { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
  // Force HTTPS pendant 2 ans une fois servi en HTTPS (sans effet en dev HTTP).
  { key: "Strict-Transport-Security", value: "max-age=63072000; includeSubDomains; preload" },
  // CSP en mode Report-Only : observe les violations sans bloquer quoi que ce soit.
  // Passer à "Content-Security-Policy" une fois que les violations sont nulles en production.
  { key: "Content-Security-Policy-Report-Only", value: CSP },
];

const nextConfig: NextConfig = {
  allowedDevOrigins: ["127.0.0.1", "localhost"],
  experimental: {
    serverActions: {
      // *.vercel.app était trop large (n'importe quel projet Vercel pourrait
      // envoyer des requêtes Server Action). On le remplace par le seul hôte
      // de production réel. La variante générique est conservée en commentaire.
      allowedOrigins: [
        "localhost:3000",
        "127.0.0.1:3000",
        "192.168.178.129:3000",
        "suivi-horaire.vercel.app",
        // "*.vercel.app", // trop large — remplacé par l'hôte exact ci-dessus
      ],
    },
  },
  async headers() {
    return [
      {
        source: "/:path*",
        headers: securityHeaders,
      },
    ];
  },
};

export default nextConfig;
